{{ if .Values.global.externalSecrets.deploy }}
{{- if not .Values.externalSecrets.createK8sJwtKeysSecret}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: analysis-jwt-keys
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: analysis-jwt-keys
    creationPolicy: Owner
  data:
  - secretKey: jwt_private_key.pem
    remoteRef:
      #name of secret in secrets manager
      key: {{include "analysis-jwt-keys" .}}
---
{{- end }}
{{- if and (.Values.global.externalSecrets.deploy) (not .Values.global.externalSecrets.dbCreate) }}
{{ include "common.externalSecret.db" . }}
{{- end}}
{{- end}}